### ISSUE TITLE
REmove all xliff tags

### ISSUE THREAD

**Issue by ingbrzy** [PRInCEI7/MIUI-8-ARABIC#2]
REMOVE all xliff tags but keep variables like I did here
https://github.com/PRInCEI7/MIUI-8-ARABIC/commit/f9ced7e063b38b962aceedd8510696720e75bf92

**Comment by ingbrzy** [comment]
after that I can include it in our roms..

**Comment by BASHEER-A** [comment]
@ingbrzy   

 Thank you for your interest in our society
I've modified all files
Without deleting the value 
You can check now

**Comment by ingbrzy** [comment]
still not removed from all files...
https://github.com/PRInCEI7/MIUI-8-ARABIC/search?utf8=%E2%9C%93&q=xliff

**Comment by BASHEER-A** [comment]
@ingbrzy 
Modified all files
right Now
You can now check
